##########################
# extract planes
# a.k.a. Stockholm GPT
# generated by ChatGPT, 5/5/2026
##########################

import open3d as o3d
import numpy as np

#pcd = o3d.io.read_point_cloud(r"d:\stockholm.pcd")
pcd = o3d.io.read_point_cloud(r"C:\DATA\SCaffee_data\beirut_pi3\pi3_beirut_hisbollah_building_cropped.ply")

# Optional but recommended
pcd = pcd.voxel_down_sample(voxel_size=0.02)

planes = []
remaining = pcd

num_planes = 3  # how many you want

for i in range(num_planes):
    plane_model, inliers = remaining.segment_plane(
        distance_threshold=0.02,  # tune this!
        ransac_n=3,
        num_iterations=1000
    )

    [a, b, c, d] = plane_model
    print(f"Plane {i}: {a:.3f}x + {b:.3f}y + {c:.3f}z + {d:.3f} = 0")

    inlier_cloud = remaining.select_by_index(inliers)
    outlier_cloud = remaining.select_by_index(inliers, invert=True)

    planes.append((plane_model, inlier_cloud))

    remaining = outlier_cloud  # remove plane and continue


geometries = []

colors = [
    [1, 0, 0],   # red
    [0, 1, 0],   # green
    [0, 0, 1],   # blue
]

for i, (plane_model, inlier_cloud) in enumerate(planes):
    color = colors[i % len(colors)]
    inlier_cloud.paint_uniform_color(color)
    geometries.append(inlier_cloud)

# remaining points = outliers
remaining.paint_uniform_color([0.5, 0.5, 0.5])
geometries.append(remaining)


# ---------------


def clip_by_plane(pcd, plane_model, keep_above=True):
    a, b, c, d = plane_model
    points = np.asarray(pcd.points)

    # plane equation: ax + by + cz + d
    dist = points @ np.array([a, b, c]) + d

    if keep_above:
        mask = dist > 0
    else:
        mask = dist < 0

    return pcd.select_by_index(np.where(mask)[0])


clipped = clip_by_plane(pcd, planes[0][0], keep_above=True)
clipped.paint_uniform_color([1, 1, 0])  # yellow
geometries.append(clipped)



# ---------------

def get_plane_basis(normal):
    n = normal / np.linalg.norm(normal)

    arbitrary = np.array([1, 0, 0]) if abs(n[0]) < 0.9 else np.array([0, 1, 0])
    u = np.cross(n, arbitrary)
    u /= np.linalg.norm(u)
    v = np.cross(n, u)

    return u, v

def point_from_d(normal, d):
    n = np.array(normal, dtype=float)
    return (d / np.dot(n, n)) * n

def create_plane_mesh(normal, d, size=2.0, resolution=10, color=[0.5, 0.8, 0.8]):
    n = np.array(normal, dtype=float)
    p0 = point_from_d(n, d)

    u, v = get_plane_basis(n)

    # grid
    s = np.linspace(-size, size, resolution)
    t = np.linspace(-size, size, resolution)

    vertices = []
    for si in s:
        for ti in t:
            p = p0 + si * u + ti * v
            vertices.append(p)

    vertices = np.array(vertices)

    # triangles
    triangles = []
    for i in range(resolution - 1):
        for j in range(resolution - 1):
            idx = i * resolution + j
            triangles.append([idx, idx + 1, idx + resolution])
            triangles.append([idx + 1, idx + resolution + 1, idx + resolution])

    mesh = o3d.geometry.TriangleMesh()
    mesh.vertices = o3d.utility.Vector3dVector(vertices)
    mesh.triangles = o3d.utility.Vector3iVector(triangles)

    mesh.paint_uniform_color(color)
    mesh.compute_vertex_normals()

    return mesh

# ---------------

def plane_mesh_from_points(plane_model, cloud, color=[0,1,1]):
    a, b, c, d = plane_model
    n = np.array([a, b, c])
    n = n / np.linalg.norm(n)

    points = np.asarray(cloud.points)

    # --- 1. build plane basis
    u, v = get_plane_basis(n)

    # --- 2. project to 2D plane coordinates
    origin = points.mean(axis=0)

    rel = points - origin
    u_coords = rel @ u
    v_coords = rel @ v


## (A)
    # pts_2d = np.stack([u_coords, v_coords], axis=1)

    # # --- 3. convex hull in 2D
    # hull = o3d.geometry.PointCloud()
    # hull.points = o3d.utility.Vector3dVector(
    #     np.column_stack([u_coords, v_coords, np.zeros_like(u_coords)])
    # )

    # hull_mesh, _ = hull.compute_convex_hull()

    # hull_vertices_2d = np.asarray(hull_mesh.vertices)[:, :2]

    # # --- 4. map back to 3D
    # vertices_3d = []
    # for uv in hull_vertices_2d:
    #     p = origin + uv[0]*u + uv[1]*v
    #     vertices_3d.append(p)
## QH6154 Qhull precision error: Initial simplex is flat

## (B)
    # vertices_3d = np.array(vertices_3d)
    u_min, u_max = u_coords.min(), u_coords.max()
    v_min, v_max = v_coords.min(), v_coords.max()
    
    corners = np.array([
        [u_min, v_min],
        [u_max, v_min],
        [u_max, v_max],
        [u_min, v_max]
    ])
    
    vertices_3d = origin + corners[:,0:1]*u + corners[:,1:2]*v
## ---

    # --- 5. triangulate (fan)
    triangles = []
    for i in range(1, len(vertices_3d)-1):
        triangles.append([0, i, i+1])

    mesh = o3d.geometry.TriangleMesh()
    mesh.vertices = o3d.utility.Vector3dVector(vertices_3d)
    mesh.triangles = o3d.utility.Vector3iVector(triangles)

    mesh.paint_uniform_color(color)
    mesh.compute_vertex_normals()

    return mesh

# ---------------


def plane_to_mesh(plane_model, size=2, color=[0,1,1]):
    a, b, c, d = plane_model
    normal = np.array([a, b, c])
    return create_plane_mesh(normal, -d, size=size, color=color)

# a) planes
# for plane_model, _ in planes:
#     mesh = plane_to_mesh(plane_model, size=2)
#     geometries.append(mesh)

# b) meshes (planes clipped to observed points)
for i, (plane_model, inlier_cloud) in enumerate(planes):
    mesh = plane_mesh_from_points(
        plane_model,
        inlier_cloud,
        color=[1, 0, 0] if i == 0 else [0, 1, 0]
    )
    geometries.append(mesh)
    
    
o3d.visualization.draw_geometries(geometries)